# Generated by Django 4.2.7 on 2023-11-14 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descritpiton',
            new_name='description',
        ),
    ]
